# Generated by Django 4.2.5 on 2023-09-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingfilter',
            options={'verbose_name': 'Фильтр рассылки', 'verbose_name_plural': 'Фильтры рассылок'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='mailingfilter',
            old_name='filter_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('in_progress', 'В процессе'), ('done', 'Закончена')], default='waiting', max_length=20, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingfilter',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_filters', to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус сообщения'),
        ),
    ]
