# Generated by Django 4.2.5 on 2023-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingfilter',
            name='filter_type',
            field=models.CharField(choices=[('tag', 'Фильтр по тегу'), ('mobile_code', 'Фильтр по коду оператора')], max_length=100, verbose_name='Тип фильтра'),
        ),
    ]
