version: "3.9"

services:
  web:
    build: .
    entrypoint: /notifications/start.sh  
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
